version: "3.8"
services:
  health:
    container_name: gprs-client
    image: ghcr.io/slntopp/nocloud/health:latest
    networks:
      - grpc-internal
  apiserver-web:
    container_name: gprs-server
    image: ghcr.io/slntopp/nocloud/apiserver-web:latest
    environment:
      APISERVER_HOST: apiserver:8080
    ports:
      - 10000:10000 # REST-API
    networks:
      - grpc-internal

networks:
  grpc-internal:
  arangodb:
    driver: bridge

volumes:
  data:
