// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: pkg/proto/tunnel.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InitConnection Messages for path http request from server to node
//Basically server ask nodes by grpc Response and get responce by grpc Request %)
type InitConnectionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Id      uint32 `protobuf:"fixed32,2,opt,name=id,proto3" json:"id,omitempty"`
	Json    []byte `protobuf:"bytes,3,opt,name=json,proto3" json:"json,omitempty"`
}

func (x *InitConnectionResponse) Reset() {
	*x = InitConnectionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_tunnel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitConnectionResponse) ProtoMessage() {}

func (x *InitConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_tunnel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitConnectionResponse.ProtoReflect.Descriptor instead.
func (*InitConnectionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *InitConnectionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InitConnectionResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InitConnectionResponse) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

type InitConnectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Id      uint32 `protobuf:"fixed32,2,opt,name=id,proto3" json:"id,omitempty"`
	Json    []byte `protobuf:"bytes,3,opt,name=json,proto3" json:"json,omitempty"`
}

func (x *InitConnectionRequest) Reset() {
	*x = InitConnectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_tunnel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitConnectionRequest) ProtoMessage() {}

func (x *InitConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_tunnel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitConnectionRequest.ProtoReflect.Descriptor instead.
func (*InitConnectionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *InitConnectionRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InitConnectionRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InitConnectionRequest) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

// LogConnection Messages for path own Docker container logs to server
type LogConnectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Log string `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
}

func (x *LogConnectionRequest) Reset() {
	*x = LogConnectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_tunnel_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogConnectionRequest) ProtoMessage() {}

func (x *LogConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_tunnel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogConnectionRequest.ProtoReflect.Descriptor instead.
func (*LogConnectionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *LogConnectionRequest) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

type LogConnectionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TsStart uint64 `protobuf:"fixed64,1,opt,name=ts_start,json=tsStart,proto3" json:"ts_start,omitempty"`
	Follow  bool   `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"`
	Stop    bool   `protobuf:"varint,3,opt,name=stop,proto3" json:"stop,omitempty"`
}

func (x *LogConnectionResponse) Reset() {
	*x = LogConnectionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_tunnel_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogConnectionResponse) ProtoMessage() {}

func (x *LogConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_tunnel_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogConnectionResponse.ProtoReflect.Descriptor instead.
func (*LogConnectionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_tunnel_proto_rawDescGZIP(), []int{3}
}

func (x *LogConnectionResponse) GetTsStart() uint64 {
	if x != nil {
		return x.TsStart
	}
	return 0
}

func (x *LogConnectionResponse) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *LogConnectionResponse) GetStop() bool {
	if x != nil {
		return x.Stop
	}
	return false
}

// Pathing couples Fingerprint-Host from DB
type HostFingerprint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fingerprint string `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Host        string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
}

func (x *HostFingerprint) Reset() {
	*x = HostFingerprint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_tunnel_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostFingerprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostFingerprint) ProtoMessage() {}

func (x *HostFingerprint) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_tunnel_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostFingerprint.ProtoReflect.Descriptor instead.
func (*HostFingerprint) Descriptor() ([]byte, []int) {
	return file_pkg_proto_tunnel_proto_rawDescGZIP(), []int{4}
}

func (x *HostFingerprint) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *HostFingerprint) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

//Pathing logs from server to admin panel
type LogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Log string `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_tunnel_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_tunnel_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_tunnel_proto_rawDescGZIP(), []int{5}
}

func (x *LogRequest) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

type LogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TsStart uint64 `protobuf:"fixed64,1,opt,name=ts_start,json=tsStart,proto3" json:"ts_start,omitempty"`
	Follow  bool   `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"`
	Stop    bool   `protobuf:"varint,3,opt,name=stop,proto3" json:"stop,omitempty"`
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_tunnel_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_tunnel_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_tunnel_proto_rawDescGZIP(), []int{6}
}

func (x *LogResponse) GetTsStart() uint64 {
	if x != nil {
		return x.TsStart
	}
	return 0
}

func (x *LogResponse) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *LogResponse) GetStop() bool {
	if x != nil {
		return x.Stop
	}
	return false
}

var File_pkg_proto_tunnel_proto protoreflect.FileDescriptor

var file_pkg_proto_tunnel_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x75, 0x6e, 0x6e,
	0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c,
	0x22, 0x56, 0x0a, 0x16, 0x49, 0x6e, 0x69, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x07,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x22, 0x55, 0x0a, 0x15, 0x49, 0x6e, 0x69, 0x74,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x07, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6a,
	0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x22,
	0x28, 0x0a, 0x14, 0x4c, 0x6f, 0x67, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x6f, 0x67, 0x22, 0x5e, 0x0a, 0x15, 0x4c, 0x6f, 0x67,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x73, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x06, 0x52, 0x07, 0x74, 0x73, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x66,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x22, 0x47, 0x0a, 0x0f, 0x48, 0x6f, 0x73,
	0x74, 0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b,
	0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f,
	0x73, 0x74, 0x22, 0x1e, 0x0a, 0x0a, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c,
	0x6f, 0x67, 0x22, 0x54, 0x0a, 0x0b, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x73, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x06, 0x52, 0x07, 0x74, 0x73, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x66, 0x6f,
	0x6c, 0x6c, 0x6f, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x32, 0xc4, 0x01, 0x0a, 0x17, 0x53, 0x6f, 0x63,
	0x6b, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x55, 0x0a, 0x0e, 0x49, 0x6e, 0x69, 0x74, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e,
	0x49, 0x6e, 0x69, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x49,
	0x6e, 0x69, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x52, 0x0a, 0x0d, 0x4c,
	0x6f, 0x67, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x2e, 0x74,
	0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x4c, 0x6f, 0x67, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x74, 0x75, 0x6e,
	0x6e, 0x65, 0x6c, 0x2e, 0x4c, 0x6f, 0x67, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x32,
	0x42, 0x0a, 0x0a, 0x4c, 0x6f, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a,
	0x03, 0x4c, 0x6f, 0x67, 0x12, 0x12, 0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x4c, 0x6f,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65,
	0x6c, 0x2e, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28,
	0x01, 0x30, 0x01, 0x42, 0x83, 0x01, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x75, 0x6e, 0x6e,
	0x65, 0x6c, 0x42, 0x0b, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6c,
	0x6e, 0x74, 0x6f, 0x70, 0x70, 0x2f, 0x6e, 0x6f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2d, 0x74, 0x75,
	0x6e, 0x6e, 0x65, 0x6c, 0x2d, 0x6d, 0x65, 0x73, 0x68, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0xa2, 0x02, 0x03, 0x54, 0x58, 0x58, 0xaa, 0x02, 0x06, 0x54, 0x75, 0x6e, 0x6e,
	0x65, 0x6c, 0xca, 0x02, 0x06, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0xe2, 0x02, 0x12, 0x54, 0x75,
	0x6e, 0x6e, 0x65, 0x6c, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0xea, 0x02, 0x06, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_pkg_proto_tunnel_proto_rawDescOnce sync.Once
	file_pkg_proto_tunnel_proto_rawDescData = file_pkg_proto_tunnel_proto_rawDesc
)

func file_pkg_proto_tunnel_proto_rawDescGZIP() []byte {
	file_pkg_proto_tunnel_proto_rawDescOnce.Do(func() {
		file_pkg_proto_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_tunnel_proto_rawDescData)
	})
	return file_pkg_proto_tunnel_proto_rawDescData
}

var file_pkg_proto_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_proto_tunnel_proto_goTypes = []interface{}{
	(*InitConnectionResponse)(nil), // 0: tunnel.InitConnectionResponse
	(*InitConnectionRequest)(nil),  // 1: tunnel.InitConnectionRequest
	(*LogConnectionRequest)(nil),   // 2: tunnel.LogConnectionRequest
	(*LogConnectionResponse)(nil),  // 3: tunnel.LogConnectionResponse
	(*HostFingerprint)(nil),        // 4: tunnel.HostFingerprint
	(*LogRequest)(nil),             // 5: tunnel.LogRequest
	(*LogResponse)(nil),            // 6: tunnel.LogResponse
}
var file_pkg_proto_tunnel_proto_depIdxs = []int32{
	1, // 0: tunnel.SocketConnectionService.InitConnection:input_type -> tunnel.InitConnectionRequest
	2, // 1: tunnel.SocketConnectionService.LogConnection:input_type -> tunnel.LogConnectionRequest
	5, // 2: tunnel.LogService.Log:input_type -> tunnel.LogRequest
	0, // 3: tunnel.SocketConnectionService.InitConnection:output_type -> tunnel.InitConnectionResponse
	3, // 4: tunnel.SocketConnectionService.LogConnection:output_type -> tunnel.LogConnectionResponse
	6, // 5: tunnel.LogService.Log:output_type -> tunnel.LogResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_tunnel_proto_init() }
func file_pkg_proto_tunnel_proto_init() {
	if File_pkg_proto_tunnel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_tunnel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitConnectionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_tunnel_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitConnectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_tunnel_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogConnectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_tunnel_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogConnectionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_tunnel_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostFingerprint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_tunnel_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_tunnel_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_tunnel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_proto_tunnel_proto_goTypes,
		DependencyIndexes: file_pkg_proto_tunnel_proto_depIdxs,
		MessageInfos:      file_pkg_proto_tunnel_proto_msgTypes,
	}.Build()
	File_pkg_proto_tunnel_proto = out.File
	file_pkg_proto_tunnel_proto_rawDesc = nil
	file_pkg_proto_tunnel_proto_goTypes = nil
	file_pkg_proto_tunnel_proto_depIdxs = nil
}
