// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: pkg/proto/tunnel.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HttpReQuest2Loc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Id      uint32 `protobuf:"fixed32,2,opt,name=id,proto3" json:"id,omitempty"`
	Json    []byte `protobuf:"bytes,3,opt,name=json,proto3" json:"json,omitempty"`
}

func (x *HttpReQuest2Loc) Reset() {
	*x = HttpReQuest2Loc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_tunnel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HttpReQuest2Loc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpReQuest2Loc) ProtoMessage() {}

func (x *HttpReQuest2Loc) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_tunnel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpReQuest2Loc.ProtoReflect.Descriptor instead.
func (*HttpReQuest2Loc) Descriptor() ([]byte, []int) {
	return file_pkg_proto_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *HttpReQuest2Loc) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HttpReQuest2Loc) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HttpReQuest2Loc) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

type HttpReSp4Loc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Id      uint32 `protobuf:"fixed32,2,opt,name=id,proto3" json:"id,omitempty"`
	Json    []byte `protobuf:"bytes,3,opt,name=json,proto3" json:"json,omitempty"`
}

func (x *HttpReSp4Loc) Reset() {
	*x = HttpReSp4Loc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_tunnel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HttpReSp4Loc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpReSp4Loc) ProtoMessage() {}

func (x *HttpReSp4Loc) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_tunnel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpReSp4Loc.ProtoReflect.Descriptor instead.
func (*HttpReSp4Loc) Descriptor() ([]byte, []int) {
	return file_pkg_proto_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *HttpReSp4Loc) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HttpReSp4Loc) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HttpReSp4Loc) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

type HostFingerprint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fingerprint string `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Host        string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
}

func (x *HostFingerprint) Reset() {
	*x = HostFingerprint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_tunnel_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostFingerprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostFingerprint) ProtoMessage() {}

func (x *HostFingerprint) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_tunnel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostFingerprint.ProtoReflect.Descriptor instead.
func (*HostFingerprint) Descriptor() ([]byte, []int) {
	return file_pkg_proto_tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *HostFingerprint) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *HostFingerprint) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

var File_pkg_proto_tunnel_proto protoreflect.FileDescriptor

var file_pkg_proto_tunnel_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x75, 0x6e, 0x6e,
	0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c,
	0x22, 0x4f, 0x0a, 0x0f, 0x68, 0x74, 0x74, 0x70, 0x52, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x32,
	0x4c, 0x6f, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x07, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x6a, 0x73, 0x6f,
	0x6e, 0x22, 0x4c, 0x0a, 0x0c, 0x68, 0x74, 0x74, 0x70, 0x52, 0x65, 0x53, 0x70, 0x34, 0x4c, 0x6f,
	0x63, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x07, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6a,
	0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x22,
	0x47, 0x0a, 0x0f, 0x48, 0x6f, 0x73, 0x74, 0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69,
	0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70,
	0x72, 0x69, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x32, 0x59, 0x0a, 0x10, 0x53, 0x6f, 0x63, 0x6b,
	0x65, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x45, 0x0a, 0x0e,
	0x49, 0x6e, 0x69, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14,
	0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x52, 0x65, 0x53, 0x70,
	0x34, 0x4c, 0x6f, 0x63, 0x1a, 0x17, 0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x68, 0x74,
	0x74, 0x70, 0x52, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x32, 0x4c, 0x6f, 0x63, 0x22, 0x00, 0x28,
	0x01, 0x30, 0x01, 0x42, 0x83, 0x01, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x75, 0x6e, 0x6e,
	0x65, 0x6c, 0x42, 0x0b, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6c,
	0x6e, 0x74, 0x6f, 0x70, 0x70, 0x2f, 0x6e, 0x6f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2d, 0x74, 0x75,
	0x6e, 0x6e, 0x65, 0x6c, 0x2d, 0x6d, 0x65, 0x73, 0x68, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0xa2, 0x02, 0x03, 0x54, 0x58, 0x58, 0xaa, 0x02, 0x06, 0x54, 0x75, 0x6e, 0x6e,
	0x65, 0x6c, 0xca, 0x02, 0x06, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0xe2, 0x02, 0x12, 0x54, 0x75,
	0x6e, 0x6e, 0x65, 0x6c, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0xea, 0x02, 0x06, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_pkg_proto_tunnel_proto_rawDescOnce sync.Once
	file_pkg_proto_tunnel_proto_rawDescData = file_pkg_proto_tunnel_proto_rawDesc
)

func file_pkg_proto_tunnel_proto_rawDescGZIP() []byte {
	file_pkg_proto_tunnel_proto_rawDescOnce.Do(func() {
		file_pkg_proto_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_tunnel_proto_rawDescData)
	})
	return file_pkg_proto_tunnel_proto_rawDescData
}

var file_pkg_proto_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_proto_tunnel_proto_goTypes = []interface{}{
	(*HttpReQuest2Loc)(nil), // 0: tunnel.httpReQuest2Loc
	(*HttpReSp4Loc)(nil),    // 1: tunnel.httpReSp4Loc
	(*HostFingerprint)(nil), // 2: tunnel.HostFingerprint
}
var file_pkg_proto_tunnel_proto_depIdxs = []int32{
	1, // 0: tunnel.SocketConnection.InitConnection:input_type -> tunnel.httpReSp4Loc
	0, // 1: tunnel.SocketConnection.InitConnection:output_type -> tunnel.httpReQuest2Loc
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_tunnel_proto_init() }
func file_pkg_proto_tunnel_proto_init() {
	if File_pkg_proto_tunnel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_tunnel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HttpReQuest2Loc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_tunnel_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HttpReSp4Loc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_tunnel_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostFingerprint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_tunnel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_tunnel_proto_goTypes,
		DependencyIndexes: file_pkg_proto_tunnel_proto_depIdxs,
		MessageInfos:      file_pkg_proto_tunnel_proto_msgTypes,
	}.Build()
	File_pkg_proto_tunnel_proto = out.File
	file_pkg_proto_tunnel_proto_rawDesc = nil
	file_pkg_proto_tunnel_proto_goTypes = nil
	file_pkg_proto_tunnel_proto_depIdxs = nil
}
